[package]
name = "is-odd-overengineer"
version = "0.1.0"
edition = "2024"

[dependencies]
actix-web = "4"
env_logger = "0.11.7"
log = "0.4.26"
serde = { version = "1", features = ["derive"] }
serde_json = "1.0.140"
